/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.dev.hygino.app;

import br.dev.hygino.dto.RequestGameDto;
import br.dev.hygino.dto.ResponseGameDto;
import br.dev.hygino.model.Game;
import br.dev.hygino.service.GameService;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hygino
 */
public class GameApp extends javax.swing.JFrame {

    private GameService service = GameService.getInstance();

    private List<ResponseGameDto> gamelist;

    private DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GameApp.class.getName());

    /**
     * Creates new form GameApp
     */
    public GameApp() {
        setTitle("Gerenciador de jogos");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lbDeeveloper = new javax.swing.JLabel();
        txtDeveloper = new javax.swing.JTextField();
        lbDate = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        lbConsole = new javax.swing.JLabel();
        cbConsoles = new javax.swing.JComboBox<>();
        lbCode = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        lbGenre = new javax.swing.JLabel();
        txtGenre = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        lbStatus = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbGames = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbName.setText("Nome");

        lbDeeveloper.setText("Desenvolvedora");

        lbDate.setText("Lançamento");

        lbConsole.setText("Console");

        cbConsoles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Mega Drive", "Super Nintendo", "Nintendo", "Nintendo 64", "Nintendo WII", "XBOX", "XBOX 360", "XBOX ONE", "PlayStation", "PlayStation 2", "PlayStation 3", "PlayStation 4", "PlayStation 5" }));

        lbCode.setText("Código");

        lbGenre.setText("Gênero");

        btnClear.setBackground(new java.awt.Color(255, 102, 102));
        btnClear.setLabel("Limpar");
        btnClear.addActionListener(this::btnClearActionPerformed);

        btnFind.setBackground(new java.awt.Color(204, 255, 204));
        btnFind.setLabel("Buscar");
        btnFind.addActionListener(this::btnFindActionPerformed);

        btnSave.setBackground(new java.awt.Color(102, 102, 255));
        btnSave.setLabel("Salvar");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        lbStatus.setText("STATUS");

        tbGames.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "#", "Nome", "Console", "Desenvolvedora", "Lançamento", "Código", "Gênero"
            }
        ));
        tbGames.setShowGrid(true);
        jScrollPane1.setViewportView(tbGames);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbGenre, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbCode, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbName)
                                            .addGap(85, 85, 85)
                                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(lbDeeveloper)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(lbDate)
                                                        .addGap(48, 48, 48)))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(lbConsole)
                                                    .addGap(72, 72, 72)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtDeveloper, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cbConsoles, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnClear)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnFind)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSave)))))
                        .addGap(510, 510, 510))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDeeveloper)
                    .addComponent(txtDeveloper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDate)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbConsole)
                    .addComponent(cbConsoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCode)
                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGenre)
                    .addComponent(txtGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear)
                    .addComponent(btnFind)
                    .addComponent(btnSave))
                .addGap(18, 18, 18)
                .addComponent(lbStatus)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearFields();
    }//GEN-LAST:event_btnClearActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        loadData(null, null, null);
    }//GEN-LAST:event_formWindowOpened

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        saveGame();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        findGames();
    }//GEN-LAST:event_btnFindActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GameApp().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbConsoles;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCode;
    private javax.swing.JLabel lbConsole;
    private javax.swing.JLabel lbDate;
    private javax.swing.JLabel lbDeeveloper;
    private javax.swing.JLabel lbGenre;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JTable tbGames;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDeveloper;
    private javax.swing.JTextField txtGenre;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

    private void clearFields() {
        txtCode.setText("");
        txtGenre.setText("");
        txtDate.setText("");
        txtDeveloper.setText("");
        txtName.setText("");
        txtName.requestFocus();
        cbConsoles.setSelectedIndex(9);
        lbStatus.setText("");
    }

    private void loadData(String name, String console, String code) {
        this.gamelist = this.service.findGames(name, console, code)
                .stream().map(Game::toGameResponse).toList();

        // Obtenha o modelo da tabela existente
        DefaultTableModel model = (DefaultTableModel) tbGames.getModel();

        // Limpe todas as linhas existentes da tabela
        // Isso é importante para remover os dados antigos antes de adicionar os novos
        model.setRowCount(0);
        // Adicione os dados da sua gamelist ao modelo da tabela
        for (ResponseGameDto game : gamelist) {
            // Crie um array de objetos para cada linha.
            // A ordem dos campos aqui DEVE corresponder à ordem das colunas configuradas no NetBeans.
            // Ajuste para pegar os campos corretos da sua classe GameResponse
            Object[] rowData = {game.id(), game.name(), game.platform(), game.developer(), formatter.format(game.releaseDate()), game.personalCode(), game.genre()}; // Exemplo
            model.addRow(rowData);
        }

        // Não precisa chamar tbGames.setModel(model) novamente, pois você já pegou o modelo existente e o modificou.
        // Opcional: Se você quiser que as colunas se ajustem ao conteúdo (pode ser útil se os dados mudarem de tamanho)
        tbGames.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
    }

    private void saveGame() {
        try {
            String name = txtName.getText();
            String code = txtCode.getText();

            if (cbConsoles.getSelectedIndex() == 0) {
                throw new IllegalArgumentException("Console com opção inválida");
            }

            String console = (String) cbConsoles.getSelectedItem();
            String developer = txtDeveloper.getText();
            LocalDate releaseDate = LocalDate.parse(txtDate.getText(), formatter);
            String genre = txtGenre.getText();

            var request = new RequestGameDto(name, genre, console, releaseDate, developer, code);

            this.service.insertGame(request);
            clearFields();

            loadData(null, null, null);
        } catch (Exception e) {
            lbStatus.setText(e.getMessage());
        }
    }

    private void findGames() {
        String name = (txtName.getText().isBlank()) ? null : txtName.getText();
        String code = (txtCode.getText().isBlank()) ? null : txtCode.getText();

        String console = (cbConsoles.getSelectedIndex() == 0) ? null : cbConsoles.getSelectedItem().toString();

        System.out.printf("%s\n%s\n%s\n", name, code, console);

        loadData(name, console, code);
    }
}
